# Generated by Django 2.2.9 on 2020-02-05 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('descriere', models.CharField(blank=True, max_length=255)),
                ('ocupatie', models.CharField(blank=True, default='nespecificat', max_length=50)),
                ('nume', models.CharField(blank=True, max_length=50)),
                ('sex', models.CharField(blank=True, default='N', max_length=1)),
                ('varsta', models.PositiveIntegerField(blank=True, null=True)),
                ('buget', models.PositiveIntegerField(null=True)),
                ('telefon', models.CharField(blank=True, default='nespecificat', max_length=20)),
                ('imagine_profil', models.ImageField(blank=True, default='utilizatori/imagine_profil.svg', upload_to='utilizatori/')),
                ('cont_premium', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Utilizatori',
            },
        ),
    ]
